inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - 'Rakefile'
    - 'config.ru'
    - 'lib/**/*.rake'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'

Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#short-methods'
  # Set to 30 once all methods are fixed.
  # Max: 30
  Max: 104

# Remove the following once the code style matches
# Offense count: 59
Metrics/AbcSize:
  Max: 115

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/BlockLength:
  Max: 62

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 275

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 11

Metrics/LineLength:
  Max: 120

# Offense count: 8
Metrics/PerceivedComplexity:
  Max: 12