---
language: ruby
env: GROWSTUFF_SITE_NAME="Growstuff (travis)"
bundler_args: --without development assets production staging
rvm:
  - 2.1.1
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
